language: node_js
node_js:
    - '8.10'

branches:
    only:
        - master

before_install:
    - sudo rm -rf /usr/local/phantomjs

install:
    - npm install -g serverless

jobs:
    include:
        - stage: dev deploy
          script:
              - make deployall
