language: node_js
node_js:
    - '8.10'

branches:
    only:
        - master
install:
    - npm install -g serverless

jobs:
    include:
        - stage: dev deploy
          script:
              - make deploy
