service: yame-api

custom:
    bucket: yame-dev

provider:
    name: aws
    runtime: nodejs8.10
    stage: ${opt:stage}
    region: ap-southeast-2
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:GetItem
              - dynamodb:UpdateItem
          Resource: 'arn:aws:dynamodb:${self:provider.region, self:provider.region}:*:table/DocumentAccess'
        - Effect: Allow
          Action:
              - s3:*
          Resource: 'arn:aws:s3:::${self:custom.bucket}/*'
        - Effect: Allow
          Action:
              - s3:*
          Resource: 'arn:aws:s3:::${self:custom.bucket}'

functions:
    app:
        handler: dist/handler.handler
        events:
            - http: ANY /
            - http: 'ANY {proxy+}'
plugins:
    - serverless-offline

resources:
    Resources:
        DocumentAccessTable:
            Type: 'AWS::DynamoDB::Table'
            Properties:
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                    - AttributeName: permalink
                      AttributeType: S
                    - AttributeName: userId
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
                TableName: DocumentAccess
                GlobalSecondaryIndexes:
                    IndexName: ‘urlAccess'
                    KeySchema:
                        - AttributeName: userId
                          KeyType: HASH
                        - AttributeName: permalink
                          KeyType: RANGE
                    ProvisionedThroughput:
                        ReadCapacityUnits: 1
                        WriteCapacityUnits: 1
