service: yame-api

custom:
    localbucket: yame-local
    devbucket: yame-dev
    customDomain:
        domainName: ${self:custom.domainNames.${self:provider.stage}}
        certificateName: ${self:custom.certificateNames.${self:provider.stage}}
        basePath: ''
        stage: ${self:provider.stage}
        createRoute53Record: true
    domainNames:
        dev: api.dev.yame.io
        prod: api.yame.io
    certificateNames:
        dev: '*.dev.yame.io'
        prod: '*.yame.io'
    apigwBinary:
        types:
            - 'application/pdf'
            - 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
            - ''
provider:
    name: aws
    runtime: nodejs8.10
    stage: ${opt:stage}
    region: ap-southeast-2
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:UpdateItem
              - dynamodb:PutItem
          Resource: 'arn:aws:dynamodb:${self:provider.region, self:provider.region}:*:table/*'
        - Effect: Allow
          Action:
              - s3:*
          Resource: 'arn:aws:s3:::${self:custom.localbucket}/*'
        - Effect: Allow
          Action:
              - s3:*
          Resource: 'arn:aws:s3:::${self:custom.localbucket}'
        - Effect: Allow
          Action:
              - s3:*
          Resource: 'arn:aws:s3:::${self:custom.devbucket}/*'
        - Effect: Allow
          Action:
              - s3:*
          Resource: 'arn:aws:s3:::${self:custom.devbucket}'
        - Effect: Allow
          Action:
              - logs:*
          Resource: '*'

functions:
    app:
        handler: dist/handler.handler
        events:
            - http:
                  path: convert/{proxy+}
                  method: get
                  cors: true
                  contentHandling: CONVERT_TO_BINARY
            - http:
                  path: download/{proxy+}
                  method: get
                  cors: true
                  contentHandling: CONVERT_TO_BINARY
            - http:
                  path: /{proxy+}
                  method: ANY
                  cors: true
                  contentHandling: CONVERT_TO_TEXT
        environment:
            FB_APP_ID: ${env:FB_APP_ID}
            FB_APP_SECRET: ${env:FB_APP_SECRET}
            BUCKET: ${env:BUCKET}
            DOC_PERMALINKS_TABLE: ${env:DOC_PERMALINKS_TABLE}
            USER_PROFILE_TABLE: ${env:USER_PROFILE_TABLE}
            STAGE: ${self:provider.stage}
plugins:
    - serverless-offline
    - serverless-domain-manager
    - serverless-apigw-binary
    - serverless-apigwy-binary

package:
    exclude:
        - src/**

resources:
    Resources:
        DocPermalinksTableLocal:
            Type: 'AWS::DynamoDB::Table'
            Properties:
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                    - AttributeName: permalink
                      AttributeType: S
                    - AttributeName: userId
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
                TableName: DocPermalinks-local
                GlobalSecondaryIndexes:
                    - IndexName: userIdPermalinkIndex
                      KeySchema:
                          - AttributeName: userId
                            KeyType: HASH
                          - AttributeName: permalink
                            KeyType: RANGE
                      Projection:
                          ProjectionType: ALL
                      ProvisionedThroughput:
                          ReadCapacityUnits: 1
                          WriteCapacityUnits: 1
        DocPermalinksTableDev:
            Type: 'AWS::DynamoDB::Table'
            Properties:
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                    - AttributeName: permalink
                      AttributeType: S
                    - AttributeName: userId
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
                TableName: DocPermalinks-dev
                GlobalSecondaryIndexes:
                    - IndexName: userIdPermalinkIndex
                      KeySchema:
                          - AttributeName: userId
                            KeyType: HASH
                          - AttributeName: permalink
                            KeyType: RANGE
                      Projection:
                          ProjectionType: ALL
                      ProvisionedThroughput:
                          ReadCapacityUnits: 1
                          WriteCapacityUnits: 1
        UserProfileTableLocal:
            Type: 'AWS::DynamoDB::Table'
            Properties:
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                    - AttributeName: username
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
                TableName: UserProfile-local
                GlobalSecondaryIndexes:
                    - IndexName: nameIndex
                      KeySchema:
                          - AttributeName: username
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL
                      ProvisionedThroughput:
                          ReadCapacityUnits: 1
                          WriteCapacityUnits: 1
        UserProfileTableDev:
            Type: 'AWS::DynamoDB::Table'
            Properties:
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                    - AttributeName: username
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 1
                    WriteCapacityUnits: 1
                TableName: UserProfile-dev
                GlobalSecondaryIndexes:
                    - IndexName: nameIndex
                      KeySchema:
                          - AttributeName: username
                            KeyType: HASH
                      Projection:
                          ProjectionType: ALL
                      ProvisionedThroughput:
                          ReadCapacityUnits: 1
                          WriteCapacityUnits: 1
